package com.squads.app.auth

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.GeneralSecurityException
import java.security.KeyStore
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Encrypts and decrypts short secrets to and from a self-contained string.
 * Implementations throw on any failure; callers decide how to recover.
 */
interface TokenCipher {
    fun encrypt(plaintext: String): String

    fun decrypt(encoded: String): String
}

/**
 * AES-256/GCM with a non-exportable key held in AndroidKeyStore.
 *
 * Output format: `v1:<base64 IV>:<base64 ciphertext+tag>`. The IV is generated by the
 * Keystore on every encryption (randomized encryption is enforced for GCM keys).
 */
class KeystoreTokenCipher(
    private val keyAlias: String = KEY_ALIAS,
) : TokenCipher {
    override fun encrypt(plaintext: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        val encoder = Base64.getEncoder()
        val iv = encoder.encodeToString(cipher.iv)
        val body = encoder.encodeToString(ciphertext)
        return "$FORMAT_VERSION$SEPARATOR$iv$SEPARATOR$body"
    }

    override fun decrypt(encoded: String): String {
        val parts = encoded.split(SEPARATOR)
        if (parts.size != 3 || parts[0] != FORMAT_VERSION) {
            throw GeneralSecurityException("Unrecognized ciphertext format")
        }
        val decoder = Base64.getDecoder()
        val iv = decoder.decode(parts[1])
        val ciphertext = decoder.decode(parts[2])
        val key = loadKey() ?: throw GeneralSecurityException("Keystore key missing")
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, iv))
        return String(cipher.doFinal(ciphertext), Charsets.UTF_8)
    }

    private fun loadKey(): SecretKey? {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        return keyStore.getKey(keyAlias, null) as? SecretKey
    }

    private fun getOrCreateKey(): SecretKey = loadKey() ?: generateKey()

    private fun generateKey(): SecretKey {
        val purposes = KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        val spec =
            KeyGenParameterSpec
                .Builder(keyAlias, purposes)
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                .build()
        val generator =
            KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(spec)
        return generator.generateKey()
    }

    companion object {
        const val KEY_ALIAS = "squads_refresh_token"
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val KEY_SIZE_BITS = 256
        private const val GCM_TAG_BITS = 128
        private const val FORMAT_VERSION = "v1"
        private const val SEPARATOR = ":"
    }
}
